/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scheep.UI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import scheep.Board;
import scheep.Coordinates;
import scheep.Highscore;
import scheep.Highscores;

/**
 *
 * @author vforteli
 */
public class ScheepGUI extends javax.swing.JFrame
{
    Highscores scores = null;
    
    
    /**
     * Creates new form ScheepGUI
     */
    public ScheepGUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        HighScoresFrame = new javax.swing.JFrame();
        ResetHighScoresButton = new javax.swing.JButton();
        HighscoresTable = new javax.swing.JTable();
        NewScoreFrame = new javax.swing.JFrame();
        SaveScoreNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SaveScoreButton = new javax.swing.JButton();
        BoardPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        CoordinatesBox = new javax.swing.JTextField();
        FireButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TurnsLabel = new javax.swing.JLabel();
        MainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        NewGameButton = new javax.swing.JMenuItem();
        ShowHighscoresButton = new javax.swing.JMenuItem();

        HighScoresFrame.setTitle("High scores");
        HighScoresFrame.setMinimumSize(new java.awt.Dimension(300, 200));
        HighScoresFrame.setName("HighscoresFrame"); // NOI18N

        ResetHighScoresButton.setText("Reset");
        ResetHighScoresButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ResetHighScoresButtonActionPerformed(evt);
            }
        });

        HighscoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Name", "Score", "Difficultyindex"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });

        javax.swing.GroupLayout HighScoresFrameLayout = new javax.swing.GroupLayout(HighScoresFrame.getContentPane());
        HighScoresFrame.getContentPane().setLayout(HighScoresFrameLayout);
        HighScoresFrameLayout.setHorizontalGroup(
            HighScoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HighScoresFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ResetHighScoresButton))
            .addComponent(HighscoresTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );
        HighScoresFrameLayout.setVerticalGroup(
            HighScoresFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HighScoresFrameLayout.createSequentialGroup()
                .addComponent(HighscoresTable, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResetHighScoresButton))
        );

        NewScoreFrame.setTitle("Save score");
        NewScoreFrame.setAlwaysOnTop(true);
        NewScoreFrame.setMaximumSize(new java.awt.Dimension(390, 120));
        NewScoreFrame.setMinimumSize(new java.awt.Dimension(390, 120));
        NewScoreFrame.setPreferredSize(new java.awt.Dimension(390, 120));
        NewScoreFrame.setResizable(false);

        jLabel2.setText("Enter name to be placed on the highscores list");

        SaveScoreButton.setText("Save");
        SaveScoreButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SaveScoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewScoreFrameLayout = new javax.swing.GroupLayout(NewScoreFrame.getContentPane());
        NewScoreFrame.getContentPane().setLayout(NewScoreFrameLayout);
        NewScoreFrameLayout.setHorizontalGroup(
            NewScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewScoreFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaveScoreNameTextField)
                    .addGroup(NewScoreFrameLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 149, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewScoreFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SaveScoreButton)))
                .addContainerGap())
        );
        NewScoreFrameLayout.setVerticalGroup(
            NewScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewScoreFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveScoreNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveScoreButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scheep");

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout BoardPanelLayout = new javax.swing.GroupLayout(BoardPanel);
        BoardPanel.setLayout(BoardPanelLayout);
        BoardPanelLayout.setHorizontalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        BoardPanelLayout.setVerticalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        FireButton.setText("Fire!");
        FireButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                FireButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Turns:");

        TurnsLabel.setMaximumSize(new java.awt.Dimension(31, 14));
        TurnsLabel.setMinimumSize(new java.awt.Dimension(31, 14));
        TurnsLabel.setPreferredSize(new java.awt.Dimension(31, 14));

        jMenu1.setText("File");

        NewGameButton.setText("New game");
        NewGameButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                NewGameButtonActionPerformed(evt);
            }
        });
        jMenu1.add(NewGameButton);

        ShowHighscoresButton.setText("Highscores");
        ShowHighscoresButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ShowHighscoresButtonActionPerformed(evt);
            }
        });
        jMenu1.add(ShowHighscoresButton);

        MainMenuBar.add(jMenu1);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TurnsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CoordinatesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FireButton)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CoordinatesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FireButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TurnsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    Board board = null;  
    private void NewGameButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_NewGameButtonActionPerformed
    {//GEN-HEADEREND:event_NewGameButtonActionPerformed
        // If a game is already running prompt the user for confirmation
        if (board != null)
        {
            int selection = JOptionPane.showConfirmDialog(
                                null
                        , "Do you want to discard the current game?"
                        , "New game"
                        , JOptionPane.OK_CANCEL_OPTION
                        , JOptionPane.WARNING_MESSAGE);
            
            if (selection != 0)
            {
                return;
            }
        }
        
        // Refactor?
        TurnsLabel.setText("");
        board = new Board(10);
        try 
        {
            board.AddRandomShip(5);
            board.AddRandomShip(4);
            board.AddRandomShip(3);
            board.AddRandomShip(3);
            board.AddRandomShip(2);
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(ScheepConsole.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        board.StartGame();
        DrawBoard();
    }//GEN-LAST:event_NewGameButtonActionPerformed

    
    private void DrawBoard()
    {
        if (board != null)
        {  
            Board.cellstate[][] b = board.GetBoard();
            System.out.print("\t");
            for (int x = 0; x < b[0].length; x++)
            {
                 System.out.print(" " + (char)(x + 97) + " ");
            }
            System.out.println();
            System.out.println();

            int i = 0;
            for (Board.cellstate[] row : b)
            {
                System.out.print(++i + "\t");
                for (Board.cellstate cell : row)
                {
                   if (cell == Board.cellstate.Ship)         
                   {
                       //System.out.print(" # ");   // Uncomment to enable "god mode"
                       System.out.print(" ~ ");
                   }
                   else if (cell == Board.cellstate.Hit)         
                   {
                       System.out.print(" X ");
                   }
                   else if (cell == Board.cellstate.Miss)         
                   {
                       System.out.print(" O ");
                   }
                   else if (cell == null)
                   {
                       System.out.print(" ~ ");
                   }     
                }
                System.out.println();
            }
        }
    }
    
    
    
    
    

    private void ShowHighscoresButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ShowHighscoresButtonActionPerformed
    {//GEN-HEADEREND:event_ShowHighscoresButtonActionPerformed
        ShowHighscores();
    }//GEN-LAST:event_ShowHighscoresButtonActionPerformed

    
    /*
     * Show the highscores popup
     */
    private void ShowHighscores()
    {
        // Lazy load..
        if (scores == null)
        {
            scores = new Highscores();
        }
        PopulateHighscoresTable();
        HighScoresFrame.setVisible(true);        
    }
    
    
    private void ResetHighScoresButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ResetHighScoresButtonActionPerformed
    {//GEN-HEADEREND:event_ResetHighScoresButtonActionPerformed
        // Well, this button cannot be pressed unless the highscores have been loaded...
        this.scores.ClearHighscores();
        try
        {
            this.scores.Save();
        } 
        catch (IOException ex)
        {
            Logger.getLogger(ScheepGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Refresh the list to show the changes
        PopulateHighscoresTable();        
    }//GEN-LAST:event_ResetHighScoresButtonActionPerformed

    
    private void FireButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_FireButtonActionPerformed
    {//GEN-HEADEREND:event_FireButtonActionPerformed
        GameCompleted();    // Debug
        if (CoordinatesBox.getText() != null)
        {
            Coordinates c = Coordinates.ParseCoordinates((CoordinatesBox.getText()));
            try
            {
                board.Fire(c.x, c.y);
                DrawBoard();
                
                TurnsLabel.setText(Integer.toString(board.getFireCount()));
                
                if (board.getShipcells() == 0)
                {
                    GameCompleted();
                }
            } 
            catch (Exception ex)
            {
                // Notify the user? although, with a clickable GUI this should not be an issue anyway...
                Logger.getLogger(ScheepGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_FireButtonActionPerformed

    
    private void SaveScoreButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveScoreButtonActionPerformed
    {//GEN-HEADEREND:event_SaveScoreButtonActionPerformed
        if (scores == null)
        {
            scores = new Highscores();
        }
        Highscore h = new Highscore();
        h.Name = SaveScoreNameTextField.getText();
        h.Score = board.getScore();
        scores.AddHighscore(h);
        try
        {
            scores.Save();
        } 
        catch (IOException ex)
        {
            Logger.getLogger(ScheepGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        NewScoreFrame.dispose();
        SaveScoreNameTextField.setText(null);
        ShowHighscores();
    }//GEN-LAST:event_SaveScoreButtonActionPerformed

    
    /*
     * Called when a game is completed
     */
    private void GameCompleted()
    {
        NewScoreFrame.setVisible(true);
        // Get name for highscore
        
        // Save highscore
        
        // Show highscores?
        
        // Reset state
    }    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ScheepGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ScheepGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ScheepGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ScheepGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ScheepGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JTextField CoordinatesBox;
    private javax.swing.JButton FireButton;
    private javax.swing.JFrame HighScoresFrame;
    private javax.swing.JTable HighscoresTable;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenuItem NewGameButton;
    private javax.swing.JFrame NewScoreFrame;
    private javax.swing.JButton ResetHighScoresButton;
    private javax.swing.JButton SaveScoreButton;
    private javax.swing.JTextField SaveScoreNameTextField;
    private javax.swing.JMenuItem ShowHighscoresButton;
    private javax.swing.JLabel TurnsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    
    
    /**
     * Populate the high scores frame table with highscores
     */
    private void PopulateHighscoresTable()
    {
        HighscoresTable.removeAll(); 
        DefaultTableModel model = new javax.swing.table.DefaultTableModel(); 
        model.addColumn("Name");
        model.addColumn("Score");
        model.addColumn("Difficulty");
        if (scores != null)
        {
            for (Highscore s : scores.getHighscores())
            {
                model.addRow(new Object[] { s.Name, s.Score, 0}); 
                System.out.println(s.Name + ": " + s.Score);                
            }
        }
        HighscoresTable.setModel(model);
    }
}
